const uiColors = {
  uiPrimary: '#3377FF',
  uiPrimaryDark: '#2659BF',
  uiPrimaryLight: '#99BBFF',
  uiPrimarySubtle: '#E3EDFF',
  uiError: '#FF3B3B',
  uiErrorDark: '#',
  uiErrorLight: '#',
  uiErrorSubtle: '#',
  uiInfo: '#0063F7',
  uiInfoDark: '#',
  uiInfoLight: '#',
  uiInfoSubtle: '#',
  uiWarning: '#FFCC00',
  uiWarningDark: '#',
  uiWarningLight: '#',
  uiWarningSubtle: '#',
  uiSuccess: '#06C270',
  uiSuccessDark: '#',
  uiSuccessLight: '#',
  uiSuccessSubtle: '#',
  uiDark1: '#3A3A3C',
  uiDark2: '#6B7588',
  uiDark3: '#8F90A6',
  uiDark4: '#C7C9D9',
  uiLight1: '#DDE5E9',
  uiLight2: '#EBEBFO',
  uiLight3: '#F2F2F5',
  uiLight4: '#FAFAFC',
  uiWhite: '#FFFFFF',
  uiBlack: '#000000',
  uiTransparent: 'transparent',
};

module.exports = uiColors;
